# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "My eval"

prompts:
  - "Write a tweet about {{topic}}"
  

providers:
  # - "openai:gpt-4o-mini"
  # - "openai:gpt-4o"
  # - "anthropic:messages:claude-3-5-sonnet-20240620"
  # - "anthropic:messages:claude-3-opus-20240307"
  # - "ollama:chat:llama3"
  - "ollama:chat:mixtral:8x22b"
  

tests:
  - vars:
      topic: bananas

  - vars:
      topic: avocado toast
    assert:
      # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs

      # Make sure output contains the word "avocado"
      - type: icontains
        value: avocado

      # Prefer shorter outputs
      - type: javascript
        value: 1 / (output.length + 1)

  # - vars:
  #     topic: new york city
  #   assert:
  #     # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
  #     - type: llm-rubric
  #       value: ensure that the output is funny

